---
name: "pr build"
on:
    pull_request

jobs:
  pre-release:
    name: "pre-release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source"
        uses: actions/checkout@v2

      - name: "Build artifacts"
        run: |
          ARCH=rm make docker
          ARCH=kobo make docker

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/

